@server = http://localhost:8080


### UTCLOrderService.Order
POst {{server}}/odata/v4/UTCLOrderService/Order
Content-Type: application/json

{

    "id" : "573ca4e5-3f25-4f2a-8225-1cd397745c59",
    "status" : "Pending"

}


### UTCLOrderService.UTCLCustomer
GET {{server}}/odata/v4/UTCLOrderService/UTCLCustomer
Content-Type: application/json


### UTCLOrderService.UTCLAddress
GET {{server}}/odata/v4/UTCLOrderService/UTCLAddress
Content-Type: application/json


### UTCLOrderService.UTCLCustomerType
GET {{server}}/odata/v4/UTCLOrderService/UTCLCustomerType
Content-Type: application/json
